### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by Allmedialab** [jfcherng-sublime/ST-BootstrapAutocomplete#3]
Hi,
Donated a wile ago and tried your plugin today in the latest Sublime Text Version, set on to work for Bootstrap 5, but unfortunately I don't see it working.
Regards,
David

**Comment by jfcherng** [comment]
Since you only say "it doesn't work", I may response "it works on my side".

As you can see in https://github.com/jfcherng-sublime/ST-BootstrapAutocomplete/tags. I haven't touch this plugin for a month.

1. Make sure the plugin is installed and not disabled (sometimes Package Control just disables it when updating and doesn't enables it again)
2. Is there any error message in ST console during ST starts up?
3. Give an exact case and step to reproduce your issue. By "exact", provide plugin settings, code snippet, cursor position, keystroke pressed etc. Too lazy to typing? A video is fine for sure.

**Comment by Allmedialab** [comment]
Yes you are right it was not activated! I removed it and did a new install now it works!
Thanks a lot for the quick answer!
David
